%绘制经纬度对价格的影响
%%
%完成绘图
clear,clc
SumData=xlsread('gps1','sheet1');
x=SumData(:,1);y=SumData(:,2);z=SumData(:,3);
mn1=min(x),mn2=min(y)
mx1=max(x),mx2=max(y)
[xi,yi]=meshgrid(linspace(min(x),max(x),100),linspace(min(y),max(y),100));
zi=griddata(x,y,z,xi,yi,'v4');
figure(1)
surf(xi,yi,zi);
xlabel('纬度/°','fontsize',10)
ylabel('经度/°','fontsize',10)
zlabel('价格/°','fontsize',10)
title('任务完成','fontsize',10)
%shading interp %去除网格
%%
%未完成绘图
SumData=xlsread('gps2','sheet1');
x=SumData(:,1);y=SumData(:,2);z=SumData(:,3);
[xi,yi]=meshgrid(linspace(min(x),max(x),100),linspace(min(y),max(y),100));
zi=griddata(x,y,z,xi,yi,'v4');
figure(2)
surf(xi,yi,zi);
xlabel('纬度/°','fontsize',10)
ylabel('经度/°','fontsize',10)
zlabel('价格','fontsize',10)
title('任务未完成','fontsize',10)
%shading interp %去除网格
%%
%完成与未完成绘图比较
SumData1=xlsread('gps1','sheet1');
SumData2=xlsread('gps2','sheet1');
x1=SumData1(:,1);y1=SumData1(:,2);z1=SumData1(:,3);
x2=SumData2(:,1);y2=SumData2(:,2);z2=SumData2(:,3);
[xi1,yi1]=meshgrid(linspace(min(x1),max(x1),100),linspace(min(y1),max(y1),100));
[xi2,yi2]=meshgrid(linspace(min(x2),max(x2),100),linspace(min(y2),max(y2),100));
zi1=griddata(x1,y1,z1,xi1,yi1,'v4');
zi2=griddata(x2,y2,z2,xi2,yi2,'v4');
figure(3)
surf(xi1,yi1,zi1);
shading interp %去除网格
hold on
surf(xi2,yi2,zi2);
xlabel('纬度/°','fontsize',10)
ylabel('经度/°','fontsize',10)
zlabel('价格','fontsize',10)
title('任务完成情况(无网格代表完成，有网格代表未完成)','fontsize',10)